server:
  port: 9002
spring:
  application:
      name: microserver-movie

eureka:
  instance:
    prefer-ip-address: true #优先使用ip地址注册到eureka
  client:
    register-with-eureka: true #消费方不是必须注册到eureka
    fetch-registry: true
    service-url:
     #defaultZone : http://localhost:8761/eureka/,http://localhost:8762/eureka/
     defaultZone : http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5 #刷新注册信息的间隔时间


feign:
  hystrix:
    enabled: true